### ISSUE TITLE
Minecraft is broke again

### ISSUE THREAD

**Issue by dermodmaster** [mbl-matthews/quest-to-yagni#94]
Pls help me

cant connect to server. but wanna play

wanna join faze clan?

**Comment by vMysterion** [comment]
FaZe is for losers. The only accepted Snipingcommunity in here is OpTic Gaming. Please consider this while connecting to the server, it might solve your Problem.

**Comment by dermodmaster** [comment]
### xXx_MLG_420_QU1CKSC0P3R_xXx is not amused!!!

**Comment by dermodmaster** [comment]
Hier passiert ja nix... haben die alle kein Bock mehr oder was?
![AKedOLQFNJNN2h9ALUY_e_X8IvRYugvx4-Hrhr_stOHqzA=s900-c-k-c0x00ffffff-no-rj.jpg](https://user-images.githubusercontent.com/22645685/133977003-4b3c7ab6-ea72-48c1-a339-c193ff1b68a2.jpg)

**Comment by mbl-matthews** [comment]
NullPointerExceptions müssen behandelt werden!
